name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag'
        required: false
        default: '0.6.6'
      publishReleases:
        description: 'Publish to Releases'
        required: false
        default: 'true'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2

      - name: Build Release Package
        run: |
          ./gradlew releaseProcessingLib --no-daemon
      # upload dist
      - name: Upload binaries to release
        if: ${{ github.event.inputs.publishReleases == 'true' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/*
          tag: "v${{ github.event.inputs.tag }}"
          release_name: "Version ${{ github.event.inputs.tag }}"
          body: "Prebuilt opencv-processing libs version ${{ github.event.inputs.tag }}."
          overwrite: true
          file_glob: true
          prerelease: true